### ISSUE TITLE
Error : Unable to find or load the main class SPDownloader.Main

### ISSUE THREAD

**Issue by maxlefou** [flokol120/South-Park-Downloader#10]
Can't launch the archive because of this error:

```
Error : Unable to find or load the main class SPDownloader.Main
Caused by : java.lang.NoClassDefFoundError: javafx/application/Application
```

Using Arch with kernel 5.16.5 and openjdk 17.0.1

thanks

**Comment by flokol120** [comment]
I suspect you were trying to use v0.6.1. As title says its outdated :D Try https://github.com/flokol120/South-Park-Downloader/releases/tag/2.0.0 But no promises this will work. I dont have much time to develop this any further. I would advice you to just use `yt-dlp https://www.southpark...`

**Comment by maxlefou** [comment]
Thanks for the tip, i didn't know about yt-dlp

I got this bug by using the one in the releases list. Maybe you should eventually tag the 2.0.0 as a release just in case anyway :p

**Comment by flokol120** [comment]
Yeah I admit that this is confusing, I'll probably just archive this project :D
