### ISSUE TITLE
Multi Language?

### ISSUE THREAD

**Issue by 93493** [flokol120/South-Park-Downloader#4]
When i click English and German Language, i have only the German one. Issue or no Multi Language Support?

**Comment by flokol120** [comment]
@93493 are you sure? You should be able to change the audio track in e.g. VLC Player whilst the later episodes are somehow of track sometimes.

**Comment by 93493** [comment]
Yes i checked in VLC the Language. There is only the German

**Comment by flokol120** [comment]
Alright. I'll have a look into it as soon as I got some free time, please be patient!

**Comment by flokol120** [comment]
@93493 I'm sorry but this will take time. This issue is due to changes by the South Park website, meaning that this will be fixed in the new, rewritten version of this downloader that I will start working on in a bit. But the rewriting itself will take time...
