### ISSUE TITLE
urlopen error [Errno -2]

### ISSUE THREAD

**Issue by Grapher2012** [flokol120/South-Park-Downloader#8]
./south-park-downloader
null
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>

finished: 1
null
[ '/home/master/Programs/shell/download/south-park-downloader-2.0.0/downloads/tempSouth Park_August 13, 1997_1_0101_South Park 0101 - Cartman Gets an Anal Probe - Act 1.mp4',
  '-o',
  '/home/master/Programs/shell/download/south-park-downloader-2.0.0/downloads/SouthPark 01.01 - null.mkv' ]
mkvmerge v8.8.0 ('Wind at my back') 64bit

mkvmerge v8.8.0 ('Wind at my back') 64bit
Ошибка: Файл '/home/master/Programs/shell/download/south-park-downloader-2.0.0/downloads/tempSouth Park_August 13, 1997_1_0101_South Park 0101 - Cartman Gets an Anal Probe - Act 1.mp4' не может быть открыт для чтения: open file error.

(node:17937) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'season' of undefined
(node:17937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: ENOENT: no such file or directory, unlink '/home/master/Programs/shell/download/south-park-downloader-2.0.0/downloads/tempSouth Park_August 13, 1997_1_0101_South Park 0101 - Cartman Gets an Anal Probe - Act 1.mp4'
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/home/master/Programs/shell/download/south-park-downloader-2.0.0/downloads/tempSouth Park_August 13, 1997_1_0101_South Park 0101 - Cartman Gets an Anal Probe - Act 1.mp4' }
(node:17937) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): undefined

**Comment by flokol120** [comment]
@Grapher2012. Sorry for not answering so long. It seems I did not get any notification about your issue. If this error still persists, please give an explanation on what you have done to produce this error.

**Comment by flokol120** [comment]
closed due to inactivity.
